# Generated by Django 4.2.7 on 2025-11-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
